Enable tflint rules
Azure/terraform-azurerm-network-security-group pull request #82
Opened 2023-01-09 23:30 UTC by Pumpkin-3906

## Describe your changes

## Issue number

#000

## Checklist before requesting a review
- [x] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [x] I have executed pre-commit on my machine
- [x] I have passed pr-check on my machine

Thanks for your cooperation!

2023-01-17 06:51 UTC, jiaweitao001 commented on modules/ActiveDirectory/output.tf
> +output "network_security_group_id" {
According to the codex, we would better name this file `outputs.tf`?

2023-01-19 06:47 UTC, lonegunmanb requested changes
It seems like we need rebase this branch from the latest master branch.

2023-01-19 22:39 UTC, lonegunmanb requested changes
Hey @Pumpkin-3906, it looks like you've merged your `tflint` branch with the `master` branch of your own forked repo, which is outdated, please sync the `master` branch of your own forked repo with upstream first, then try to merge or rebase again, thanks.

2023-01-20 10:47 UTC, lonegunmanb approved these changes
Thanks @Pumpkin-3906, LGTM 🚀

2023-01-20 10:47 UTC, merged